### ISSUE TITLE
Deploying failing

### ISSUE THREAD

**Issue by kaknut** [netlify/netlify-statuskit#55] opened 2019-05-18 16:39 UTC
10:05:59 PM: Build ready to start
10:06:02 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
10:06:02 PM: build-image tag: v3.3.2
10:06:02 PM: buildbot version: 75cd99f62ada9e21edea53208e8baf0eab85a045
10:06:03 PM: Fetching cached dependencies
10:06:03 PM: Failed to fetch cache, continuing with build
10:06:03 PM: Starting to prepare the repo for build
10:06:04 PM: No cached dependencies found. Cloning fresh repo
10:06:04 PM: git clone https://github.com/netlify/netlify-statuskit
10:06:07 PM: Preparing Git Reference refs/heads/master
10:06:07 PM: Found netlify.toml. Overriding site configuration
10:06:07 PM: Starting build script
10:06:07 PM: Installing dependencies
10:06:09 PM: v10.15.3 is already installed.
10:06:10 PM: Now using node v10.15.3 (npm v6.4.1)
10:06:10 PM: Attempting ruby version 2.6.2, read from environment
10:06:11 PM: Using ruby version 2.6.2
10:06:11 PM: Using PHP version 5.6
10:06:11 PM: Started restoring cached node modules
10:06:11 PM: Finished restoring cached node modules
10:06:11 PM: Started restoring cached yarn cache
10:06:11 PM: Finished restoring cached yarn cache
10:06:11 PM: Installing yarn at version 1.13.0
10:06:11 PM: Installing Yarn!
10:06:11 PM: > Downloading tarball...
10:06:11 PM: [1/2]: https://yarnpkg.com
10:06:11 PM: /downloads/1.13.0/yarn-v1.13.0.tar.gz --> /tmp/yarn.tar.gz.LWPuiNtVbX
10:06:11 PM:   % Total    % Received
10:06:11 PM: % Xferd  Average Speed   Time    Time     Time  Current
10:06:11 PM:                       Dload  Upload   Total
10:06:11 PM:   Spent    Left  Speed
10:06:11 PM: 
  0     0    0     0
10:06:11 PM:     0     0      0      0 --:--:-- --:--:-- --:--:--     0
10:06:12 PM: 
100    93  100    93    0     0    374      0
10:06:12 PM: --:--:-- --:--:-- --:--:--   375
10:06:12 PM: 
100   609    0   609    0     0    995      0 --:--:-- --:--:-- --:
10:06:12 PM: --:--   995
10:06:12 PM: 
  0     0    0     0    0     0      0      0 --
10:06:12 PM: :--:-- --:--:-- --:--:--     0
10:06:13 PM: 
100 1142k  100 1142k    0     0
10:06:13 PM: 1116k      0  0:00:01  0:00:01 --:--:-- 6108k
10:06:13 PM: [2/2]: https://yar
10:06:13 PM: npkg.com/downloads/1.13.0/yarn-v1.13.0.tar.gz.asc --> /tmp/yarn.tar.gz.LWPuiNtVbX.a
10:06:13 PM: sc
10:06:13 PM: 
100    97  100    97    0     0
10:06:13 PM:    2223      0 --:--:-- --:--:-- --:--:--  2223
10:06:13 PM: 
100   613    0   613    0     0   4608      0 --:--:-- --:--:-- -
10:06:13 PM: -:--:--  4608
10:06:13 PM: 
100   832  100   832    0     0   4919      0 --:--:-
10:06:13 PM: - --:--:-- --:--:--  4919
10:06:13 PM: > Verifying integrity...
10:06:13 PM: gpg: Signature made Tue 18 Dec 2018 04:04:55 PM UTC using RSA key ID B6FF4DE3
10:06:13 PM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
10:06:13 PM: gpg: Note: This key has expired!
10:06:13 PM: Primary key fingerprint:
10:06:13 PM:  72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
10:06:13 PM:      Subkey fingerprint: E219 30C4 D0A4 AA46 1858  1F7A E074 D16E B6FF 4DE3
10:06:13 PM: > GPG signature looks good
10:06:13 PM: > Extracting to ~/.yarn...
10:06:13 PM: > Adding to $PATH...
10:06:13 PM: > We've added the following to your /opt/buildhome/.profile
10:06:13 PM: > If this isn't the profile of your current shell then please add the following to your correct profile:
10:06:13 PM: export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
10:06:13 PM: 
10:06:13 PM: > Successfully installed Yarn 1.13.0! Please open another terminal where the `yarn` command will now be available.
10:06:14 PM: Installing NPM modules using Yarn version 1.13.0
10:06:15 PM: yarn install v1.13.0
10:06:15 PM: warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
10:06:15 PM: [1/4] Resolving packages...
10:06:16 PM: [2/4] Fetching packages...
10:06:27 PM: info fsevents@1.0.17: The platform "linux" is incompatible with this module.
10:06:27 PM: info "fsevents@1.0.17" is an optional dependency and failed compatibility check. Excluding it from installation.
10:06:27 PM: [3/4] Linking dependencies...
10:06:27 PM: warning " > babel-loader@6.2.10" has unmet peer dependency "babel-core@^6.0.0".
10:06:31 PM: [4/4] Building fresh packages...
10:06:31 PM: success Saved lockfile.
10:06:31 PM: Done in 16.62s.
10:06:31 PM: NPM modules installed using Yarn
10:06:32 PM: Started restoring cached go cache
10:06:32 PM: Finished restoring cached go cache
10:06:32 PM: unset GOOS;
10:06:32 PM: unset GOARCH;
10:06:32 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
10:06:32 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
10:06:32 PM: go version >&2;
10:06:32 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
10:06:32 PM: go version go1.12 linux/amd64
10:06:32 PM: Installing missing commands
10:06:32 PM: Verify run directory
10:06:32 PM: Executing user command: npm run build
10:06:32 PM: > netlify-statusKit@1.0.0 build /opt/build/repo
10:06:32 PM: > gulp build
10:06:32 PM: [16:36:32]
10:06:32 PM: Requiring external module babel-register
10:06:33 PM: gulp[1305]: ../src/node_contextify.cc:626:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
10:06:33 PM:  1: 0x8dc510 node::Abort() [gulp]
10:06:33 PM:  2: 0x8dc5e5  [gulp]
10:06:33 PM:  3: 0x91081e node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
10:06:33 PM:  4: 0xb6166b  [gulp]
10:06:33 PM:  5: 0xb63602 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
10:06:33 PM:  6: 0x615e94dbe1d
10:06:33 PM: Aborted (core dumped)
10:06:33 PM: npm
10:06:33 PM:  ERR! code ELIFECYCLE
10:06:33 PM: npm
10:06:33 PM:  ERR!
10:06:33 PM: errno
10:06:33 PM:  134
10:06:33 PM: npm
10:06:33 PM: ERR! netlify-statusKit@1.0.0 build: `gulp build`
10:06:33 PM: npm ERR! Exit status 134
10:06:33 PM: npm
10:06:33 PM:  ERR!
10:06:33 PM: npm
10:06:33 PM:  ERR! Failed at the netlify-statusKit@1.0.0 build script.
10:06:33 PM: npm ERR!
10:06:33 PM:  This is probably not a problem with npm. There is likely additional logging output above.
10:06:33 PM: npm
10:06:33 PM: ERR!
10:06:33 PM:  A complete log of this run can be found in:
10:06:33 PM: npm
10:06:33 PM: ERR!     /opt/buildhome/.npm/_logs/2019-05-18T16_36_33_261Z-debug.log
10:06:33 PM: Skipping functions preparation step: no functions directory set
10:06:33 PM: Caching artifacts
10:06:33 PM: Started saving node modules
10:06:33 PM: Finished saving node modules
10:06:33 PM: Started saving yarn cache
10:06:33 PM: Finished saving yarn cache
10:06:33 PM: Started saving pip cache
10:06:33 PM: Finished saving pip cache
10:06:33 PM: Started saving emacs cask dependencies
10:06:33 PM: Finished saving emacs cask dependencies
10:06:33 PM: Started saving maven dependencies
10:06:33 PM: Finished saving maven dependencies
10:06:33 PM: Started saving boot dependencies
10:06:33 PM: Finished saving boot dependencies
10:06:33 PM: Started saving go dependencies
10:06:33 PM: Finished saving go dependencies
10:06:35 PM: Error running command: Build script returned non-zero exit code: 134
10:06:35 PM: Failing build: Failed to build site
10:06:35 PM: failed during stage 'building site': Build script returned non-zero exit code: 134
10:06:35 PM: Finished processing build request in 32.59086766s
10:06:36 PM: Shutting down logging, 0 messages pending

**Comment by steveoh** [comment] 2019-05-28 15:33
duplicate of #57

**Closed by steveoh** 2019-05-28 15:33 UTC
